#!/usr/bin/python
import numpy as np

class A(object):
   
   @staticmethod
   def return_multiple(x,y):
     
       
     toplam = np.add(x,y)

     return toplam
       
toplam= \
A.return_multiple(5,7) 
print(np.add(5,7))


