#!/usr/bin/python

def double(x):
    return x*2

double_numbers = map(double, [2,3,5,7])

print(double_numbers)

# we only use name of outer function 
def f(x):
    z = 2
    return lambda y: z*x+y
a = 60
b = 1

print(f(a)(b)) # output is 121

"""
def area_of_rect(l,w):
    return l*w
print(f'{area_of_rect(7,8)}')
print(f'{area_of_rect(6.7,9.4)}')
"""

rect_area = lambda x,y : x*y
print(f'{rect_area(7,8)}')
print(f'{rect_area(3.4,2.9)}')

