#!/usr/bin/python

# tek satirda pyplot alt modulu import edilmistir.
#"plt" ile zaten matplotlib modulunun yaninda
# alt modul olan pyplot da kullanilmis olacaktir.
import matplotlib.pyplot as plt

radius = [1.0, 2.0, 3.0, 4.0]
area =   [3.14159, 12.56636,        
         28.27431, 50.26544]

plt.plot(radius, area)
plt.show()
