#!/usr/bin/python

import numpy as np

x = np.array ([[1,2], [3,4]], dtype=np.float64)
y = np.array ([[5,6], [7,8]], dtype=np.float64)

print(x*y)
print(np.multiply(x,y))

s = np.array([[1,2],[3,4]])
t = np.array([[5,6],[7,8]])

u = np.array([9,10])
v = np.array([11,12])

#vektor ic carpim
print(u.dot(v))
print(np.dot(u,v))

#matris vektor carpim
print(x.dot(u))
print(np.dot(x,u))

#matris matris carpim
print(x.dot(y))
print(np.dot(x,y))

