#!/usr/bin/python

import numpy as np

a = np.full((3,3), 11)
print (a)

b = np.array([[2,3,5,7], [2,4,6,8], [1,0,1,0]])
print (b)

#SLICING 
#a[:] =a[:, :-1]
#a =a[:, :-1]
#print(a)

c = np.zeros((2,2))

print(c.shape) #boyutu (2,2) verir
print(c[0].shape) #boyutu (2,) verecek = ROW
