#!/usr/bin/python

class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age
class Car:
    def __init__(self, model, color):
        self.model = model
        self.color = color

p = Person ("murat", 28)
c = Car ("EAGLE", "black")

p.age = 29
c.model = "AUDI"
print(p)
print(c)
